### ISSUE TITLE
Where does the function `parse_command_line` come from?

### ISSUE THREAD

**Issue by ketch** [mikaem/spectralDNS#2]
I assume that this function is supposed to come from

```python
   from commandline import *
```

However, `commandline` is not included in this repository and is not part of the standard library.  I tried `pip install commandline`, which installed something, but it still doesn't have `parse_command_line`.  In order to run the code, I simply commented out those lines.

Perhaps we should use the standard library's `argparse` package, or a little bit of included code?

**Comment by mikaem** [comment]
There's a file under utilities called commandline.py, check it out: https://github.com/mikaem/spectralDNS/blob/master/utilities/commandline.py

**Comment by mikaem** [comment]
Ah, you're looking at the 2D case and the import statement is wrong! Should be from utilities.commandline import *

**Comment by ketch** [comment]
This has been fixed in recent commits.
